### ISSUE TITLE
0.21.0 vs Master

### ISSUE THREAD

**Issue by ghost** [BitcoinActivation/bitcoin#11]
```
13:24 < roconnor> luke-jr: ( 2055 commits behind bitcoin:master. )
13:24 < luke-jr> roconnor: it's not based on master
13:24 < luke-jr> roconnor: it's 0.21
```
http://gnusha.org/taproot-activation/2021-04-13.log

Why is this not based on master or cannot be based on master?

**Comment by luke-jr** [comment]
Why would it be based on master? Nobody should be running master...

**Comment by ghost** [comment]
Yes normally only devs run master for testing. If this is released ignoring lot of commits from master(Core), will there be anything important that might be missing or needed for taproot?

Or we will merge everything later after next release from Core?
