### ISSUE TITLE
Tag name contains "+" character, which gitian's gbuild rejects

### ISSUE THREAD

**Issue by luke-jr** [BitcoinActivation/bitcoin#12]
gitian doesn't like the "+" character in the tag name. It's a trivial patch to fix it, but IMO it'd be better to replace it with a "." or "_" in future releases.

**Comment by ghost** [comment]
`_` will be better

**Comment by luke-jr** [comment]
For reference, not a single other release in the past seems to have used `_`:

1 used `+`: v0.5.3.1+coderrr

Mine use `.`: v0.8.6.eligius4 v0.11.2.ljrP20151118  v0.21.0.knots20210130

Most others used `-`: v0.9.0-ntxid1 v0.9.2-gitianosx v0.11.2-addrindex v0.14.2-uasfsegwit1.0 v0.14.2-segsignal

**Comment by quantumedusa** [comment]
Will use '-' for final release tag as that seems to be the convention.
