### ISSUE TITLE
Incorrect link in release notes

### ISSUE THREAD

**Issue by ghost** [BitcoinActivation/bitcoin#13]
There is a typo in the link shared here: https://github.com/BitcoinActivation/bitcoin/releases/tag/v0.21.0%2Btaproot0.1rc1

https://bitciontaproot.cc/taproot.html should be replaced by https://bitcointaproot.cc/taproot.html

Also I am not sure what happened to domain bitcointaproot.org because I was assuming that will be used for the website and everything else related to this project

**Comment by quantumedusa** [comment]
Corrected, thank you.
